-- FIX SCHEMA AND POLICIES V4 (NUCLEAR FIX)
-- Mục tiêu: Sửa lỗi "operator does not exist: uuid = bigint" bằng cách đồng bộ hóa toàn bộ kiểu dữ liệu về UUID.
-- CẢNH BÁO: Script này sẽ XÓA dữ liệu bảng groups và group_members để tạo lại cấu trúc đúng.
-- Hướng dẫn: Copy toàn bộ và chạy trong Supabase SQL Editor.

BEGIN;

-- 1. Dọn dẹp Schema cũ (Xóa các bảng/cột gây xung đột kiểu dữ liệu)
DROP FUNCTION IF EXISTS public.is_member_of_group(uuid);
DROP FUNCTION IF EXISTS public.is_member_of_group(bigint); -- Phòng hờ bản cũ dùng bigint

-- Ngắt liên kết từ bảng messages và appointments trước khi xóa groups
ALTER TABLE public.messages DROP COLUMN IF EXISTS group_id;
ALTER TABLE public.appointments DROP COLUMN IF EXISTS group_id;

-- Xóa bảng groups và group_members (CASCADE để xóa sạch ràng buộc cũ)
DROP TABLE IF EXISTS public.group_members CASCADE;
DROP TABLE IF EXISTS public.groups CASCADE;

-- 2. Tạo lại bảng GROUPS (Chuẩn UUID)
CREATE TABLE public.groups (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  avatar_url TEXT,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tạo lại bảng GROUP_MEMBERS (Chuẩn UUID)
CREATE TABLE public.group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID bản ghi vẫn là BigInt (không ảnh hưởng)
  group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin', 'member'
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_read_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(group_id, user_id)
);

-- 4. Khôi phục cột group_id cho MESSAGES và APPOINTMENTS
ALTER TABLE public.messages 
ADD COLUMN group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE;

ALTER TABLE public.appointments 
ADD COLUMN group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE;

-- 5. Bật RLS
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 6. Tạo hàm helper (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION public.is_member_of_group(_group_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.group_members 
    WHERE group_id = _group_id 
    AND user_id = auth.uid()
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.is_member_of_group(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_member_of_group(uuid) TO service_role;

-- 7. Thiết lập Policies (Đã tối ưu cho tạo nhóm)

-- === GROUPS ===
CREATE POLICY "groups_insert_policy" ON public.groups FOR INSERT
WITH CHECK (auth.uid() = created_by);

CREATE POLICY "groups_select_policy" ON public.groups FOR SELECT
USING (
    created_by = auth.uid() 
    OR 
    EXISTS (SELECT 1 FROM public.group_members WHERE group_id = id AND user_id = auth.uid())
);

CREATE POLICY "groups_update_policy" ON public.groups FOR UPDATE
USING (
    created_by = auth.uid() 
    OR 
    EXISTS (SELECT 1 FROM public.group_members WHERE group_id = id AND user_id = auth.uid() AND role = 'admin')
);

CREATE POLICY "groups_delete_policy" ON public.groups FOR DELETE
USING (auth.uid() = created_by);

-- === GROUP MEMBERS ===
CREATE POLICY "members_select_policy" ON public.group_members FOR SELECT
USING (
    user_id = auth.uid()
    OR
    EXISTS (
        SELECT 1 FROM public.group_members gm 
        WHERE gm.group_id = group_members.group_id AND gm.user_id = auth.uid()
    )
    OR
    EXISTS (
        SELECT 1 FROM public.groups g
        WHERE g.id = group_members.group_id AND g.created_by = auth.uid()
    )
);

CREATE POLICY "members_insert_policy" ON public.group_members FOR INSERT
WITH CHECK (
    user_id = auth.uid()
    OR
    EXISTS (
        SELECT 1 FROM public.groups 
        WHERE id = group_id AND created_by = auth.uid()
    )
    OR
    EXISTS (
        SELECT 1 FROM public.group_members 
        WHERE group_id = group_members.group_id 
        AND user_id = auth.uid() 
        AND role = 'admin'
    )
);

CREATE POLICY "members_delete_policy" ON public.group_members FOR DELETE
USING (
    user_id = auth.uid()
    OR
    EXISTS (
        SELECT 1 FROM public.groups 
        WHERE id = group_id AND created_by = auth.uid()
    )
    OR
    EXISTS (
        SELECT 1 FROM public.group_members 
        WHERE group_id = group_members.group_id 
        AND user_id = auth.uid() 
        AND role = 'admin'
    )
);

-- === MESSAGES (Cập nhật lại policy cho messages vì group_id mới) ===
DROP POLICY IF EXISTS "Users can see their own messages and group messages." ON public.messages;
CREATE POLICY "Users can see their own messages and group messages." ON public.messages
  FOR SELECT USING (
    auth.uid() = sender_id 
    OR auth.uid() = receiver_id 
    OR (
      group_id IS NOT NULL AND public.is_member_of_group(group_id)
    )
  );

COMMIT;

-- Force schema reload
NOTIFY pgrst, 'reload schema';
