-- FIX COMPREHENSIVE: Tạo các bảng bị thiếu (Groups, Appointments, Group Members)
-- Run this script in Supabase SQL Editor

-- 1. Create groups table if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.groups (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  avatar_url TEXT,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;

-- 2. Create group_members table if not exists
CREATE TABLE IF NOT EXISTS public.group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin', 'member'
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(group_id, user_id)
);

-- Enable RLS
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;

-- 3. Create appointments table if not exists (Fixes the 42P01 error)
CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  time TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by UUID REFERENCES public.profiles(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  contact_id UUID REFERENCES public.profiles(id), -- Nullable for group appointments
  group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE, -- Nullable for 1-on-1 appointments
  repeat_pattern TEXT DEFAULT 'none' -- 'none', 'daily', 'weekly', 'monthly'
);

-- Enable RLS
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 4. Add group_id to messages table (safely)
DO $$
BEGIN
    -- Check if messages table exists first
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'messages' AND table_schema = 'public') THEN
        -- Add group_id column if it doesn't exist
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'messages' AND column_name = 'group_id') THEN
            ALTER TABLE public.messages ADD COLUMN group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE;
        END IF;
    ELSE
        -- Create messages table if it doesn't exist (Backup plan)
        CREATE TABLE public.messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sender_id UUID REFERENCES public.profiles(id) NOT NULL,
            receiver_id UUID REFERENCES public.profiles(id),
            group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE,
            content TEXT,
            type TEXT DEFAULT 'text',
            file_url TEXT,
            priority TEXT DEFAULT 'normal',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            is_read BOOLEAN DEFAULT FALSE
        );
        ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
    END IF;
END $$;


-- =====================================================
-- HELPER FUNCTIONS (Fixes Infinite Recursion)
-- =====================================================

-- Important: Set search_path to public to prevent hijacking
-- Important: SECURITY DEFINER allows the function to run with the privileges of the creator (postgres)
-- bypassing RLS on the table it queries (group_members)
CREATE OR REPLACE FUNCTION public.is_group_member(_group_id UUID)
RETURNS BOOLEAN 
LANGUAGE plpgsql 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.group_members
    WHERE group_id = _group_id
    AND user_id = auth.uid()
  );
END;
$$;

-- Ensure postgres owns the function to bypass RLS
ALTER FUNCTION public.is_group_member(UUID) OWNER TO postgres;
GRANT EXECUTE ON FUNCTION public.is_group_member(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_group_member(UUID) TO service_role;


-- =====================================================
-- POLICIES (Quyền truy cập)
-- =====================================================

-- Groups Policies
DROP POLICY IF EXISTS "Users can view groups they are members of." ON public.groups;
CREATE POLICY "Users can view groups they are members of." ON public.groups
  FOR SELECT USING (
    public.is_group_member(id)
  );

DROP POLICY IF EXISTS "Users can create groups." ON public.groups;
CREATE POLICY "Users can create groups." ON public.groups
  FOR INSERT WITH CHECK (auth.uid() = created_by);

-- Group Members Policies
DROP POLICY IF EXISTS "Users can view members of their groups." ON public.group_members;
CREATE POLICY "Users can view members of their groups." ON public.group_members
  FOR SELECT USING (
    -- User can see themselves OR if they are a member of the group
    user_id = auth.uid() OR public.is_group_member(group_id)
  );

DROP POLICY IF EXISTS "Admins or Creators can add members." ON public.group_members;
CREATE POLICY "Admins or Creators can add members." ON public.group_members
  FOR INSERT WITH CHECK (true);

-- Appointments Policies
DROP POLICY IF EXISTS "Users can view shared appointments." ON public.appointments;
CREATE POLICY "Users can view shared appointments." ON public.appointments
  FOR SELECT USING (
    auth.uid() = created_by 
    OR auth.uid() = contact_id
    OR (
      group_id IS NOT NULL AND public.is_group_member(group_id)
    )
  );

DROP POLICY IF EXISTS "Users can create appointments." ON public.appointments;
CREATE POLICY "Users can create appointments." ON public.appointments
  FOR INSERT WITH CHECK (auth.uid() = created_by);

DROP POLICY IF EXISTS "Users can delete their own appointments." ON public.appointments;
CREATE POLICY "Users can delete their own appointments." ON public.appointments
  FOR DELETE USING (auth.uid() = created_by);

-- Messages Policies (Update)
DROP POLICY IF EXISTS "Users can see their own messages and group messages." ON public.messages;
CREATE POLICY "Users can see their own messages and group messages." ON public.messages
  FOR SELECT USING (
    auth.uid() = sender_id 
    OR auth.uid() = receiver_id 
    OR (
      group_id IS NOT NULL AND public.is_group_member(group_id)
    )
  );

-- FIX: Allow users to mark messages as read (UPDATE)
DROP POLICY IF EXISTS "Users can mark their messages as read." ON public.messages;
CREATE POLICY "Users can mark their messages as read." ON public.messages
  FOR UPDATE USING (
    auth.uid() = receiver_id
  )
  WITH CHECK (
    auth.uid() = receiver_id
  );
