-- =====================================================
-- FIX FRIEND REQUESTS ERROR (FULL SCRIPT)
-- =====================================================
-- Run this SQL in Supabase SQL Editor to create the missing table and functions.

-- 0. Ensure contacts table exists (Dependency)
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  contact_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default now(),
  unique(user_id, contact_id),
  is_pinned boolean default false,
  muted_until bigint default 0
);

alter table public.contacts enable row level security;

create policy "Users can view their own contacts." on public.contacts
  for select using (auth.uid() = user_id);

create policy "Users can add contacts." on public.contacts
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own contacts." on public.contacts
  for update using (auth.uid() = user_id);

-- 1. Create friend_requests table
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  status text default 'pending', -- 'pending', 'accepted', 'rejected'
  created_at timestamp with time zone default now(),
  unique(sender_id, receiver_id)
);

-- 2. Enable RLS
alter table public.friend_requests enable row level security;

-- 3. Create Policies
-- Allow users to view requests they sent or received
drop policy if exists "Users can view requests sent or received." on public.friend_requests;
create policy "Users can view requests sent or received." on public.friend_requests
  for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- Allow users to send requests
drop policy if exists "Users can create requests." on public.friend_requests;
create policy "Users can create requests." on public.friend_requests
  for insert with check (auth.uid() = sender_id);

-- Allow users to update requests (e.g. accept/reject) if they are the receiver
drop policy if exists "Users can update requests received." on public.friend_requests;
create policy "Users can update requests received." on public.friend_requests
  for update using (auth.uid() = receiver_id);

-- Allow users to delete requests they sent (cancel)
drop policy if exists "Users can delete requests sent." on public.friend_requests;
create policy "Users can delete requests sent." on public.friend_requests
  for delete using (auth.uid() = sender_id);

-- 4. Create function to accept friend request (RPC)
create or replace function public.accept_friend_request(request_id bigint)
returns void as $$
declare
  req record;
begin
  -- Get request info
  select * into req from public.friend_requests where id = request_id;
  
  if req is null then
    raise exception 'Request not found';
  end if;

  -- Verify receiver is current user and status is pending
  if req.receiver_id = auth.uid() and req.status = 'pending' then
    -- A. Update request status
    update public.friend_requests set status = 'accepted' where id = request_id;
    
    -- B. Add mutual friends to contacts table
    insert into public.contacts (user_id, contact_id) values (req.sender_id, req.receiver_id) on conflict do nothing;
    insert into public.contacts (user_id, contact_id) values (req.receiver_id, req.sender_id) on conflict do nothing;
  else
    raise exception 'Invalid request or permission denied';
  end if;
end;
$$ language plpgsql security definer;

-- 5. Enable Realtime for friend_requests
do $$
begin
  if not exists (select 1 from pg_publication_tables where tablename = 'friend_requests') then
    alter publication supabase_realtime add table public.friend_requests;
  end if;
exception
  when undefined_object then
    null; -- publication might not exist yet
end;
$$;
