-- Create friend_requests table
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  status text default 'pending', -- 'pending', 'accepted', 'rejected'
  created_at timestamp with time zone default now(),
  unique(sender_id, receiver_id)
);

alter table public.friend_requests enable row level security;

-- Policies
drop policy if exists "Users can view requests sent or received." on public.friend_requests;
create policy "Users can view requests sent or received." on public.friend_requests
  for select using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Users can create requests." on public.friend_requests;
create policy "Users can create requests." on public.friend_requests
  for insert with check (auth.uid() = sender_id);

drop policy if exists "Users can update requests received." on public.friend_requests;
create policy "Users can update requests received." on public.friend_requests
  for update using (auth.uid() = receiver_id);

drop policy if exists "Users can delete requests sent." on public.friend_requests;
create policy "Users can delete requests sent." on public.friend_requests
  for delete using (auth.uid() = sender_id);

-- Function to accept request
create or replace function public.accept_friend_request(request_id bigint)
returns void as $$
declare
  req record;
begin
  -- Get request info
  select * into req from public.friend_requests where id = request_id;
  
  -- Verify receiver is current user and status is pending
  if req.receiver_id = auth.uid() and req.status = 'pending' then
    -- 1. Update request status
    update public.friend_requests set status = 'accepted' where id = request_id;
    
    -- 2. Add mutual friends
    insert into public.contacts (user_id, contact_id) values (req.sender_id, req.receiver_id) on conflict do nothing;
    insert into public.contacts (user_id, contact_id) values (req.receiver_id, req.sender_id) on conflict do nothing;
  else
    raise exception 'Invalid request or permission denied';
  end if;
end;
$$ language plpgsql security definer;

-- Add to Realtime
alter publication supabase_realtime add table public.friend_requests;
