-- Migration script to create message_reactions table with UUID support and enable Realtime

-- 0. Cleanup (Safe for dev, caution in prod)
drop table if exists public.message_reactions;

-- 1. Create message_reactions table
create table public.message_reactions (
  id bigint generated by default as identity primary key,
  message_id uuid references public.messages(id) on delete cascade not null,
  user_id uuid references auth.users(id) not null,
  emoji text not null,
  created_at timestamp with time zone default now() not null,
  unique(message_id, user_id, emoji)
);

-- 2. Enable RLS
alter table public.message_reactions enable row level security;

-- 3. Create RLS policies
-- View policy
create policy "Users can see reactions for messages they can see." on public.message_reactions
  for select using (
    exists (
      select 1 from public.messages
      where id = message_reactions.message_id
      and (
        sender_id = auth.uid() 
        or receiver_id = auth.uid()
        or (group_id is not null and exists (select 1 from public.group_members where group_id = messages.group_id and user_id = auth.uid()))
      )
    )
  );

-- Insert policy
create policy "Users can add their own reactions." on public.message_reactions
  for insert with check (auth.uid() = user_id);

-- Delete policy
create policy "Users can remove their own reactions." on public.message_reactions
  for delete using (auth.uid() = user_id);

-- 4. Add to Realtime publication
-- Note: If this fails with "already member", it's fine.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'message_reactions') then
    alter publication supabase_realtime add table public.message_reactions;
  end if;
end;
$$;
